export const v78CharacterPortraits = {
  "gandalf": "/v102/gandalf-catalog-card.webp",
  "frodo-baggins": "/v78-2/characters/frodo-baggins.webp",
  "aragorn": "/v108/aragorn-catalog-card.webp",
  "galadriel": "/v107/galadriel-catalog-card.webp",
  "samwise-gamgee": "/v78-2/characters/samwise-gamgee.webp",
  "bilbo-baggins": "/v78/characters/bilbo-baggins.webp",
  "merry-brandybuck": "/v78/characters/merry-brandybuck.webp",
  "pippin-took": "/v78/characters/pippin-took.webp",
  "legolas": "/v78-2/characters/legolas.webp",
  "gimli": "/v78-2/characters/gimli.webp",
  "boromir": "/v78-2/characters/boromir.webp",
  "faramir": "/v78/characters/faramir.webp",
  "denethor": "/v78/characters/denethor.webp",
  "eowyn": "/v78-2/characters/eowyn.webp",
  "eomer": "/v78/characters/eomer.webp",
  "theoden": "/v78/characters/theoden.webp",
  "grima-wormtongue": "/v78/characters/grima-wormtongue.webp",
  "saruman": "/v78-2/characters/saruman.webp",
  "radagast": "/v78/characters/radagast.webp",
  "elrond": "/v78-2/characters/elrond.webp",
  "arwen": "/v78/characters/arwen.webp",
  "celeborn": "/v78/characters/celeborn.webp",
  "haldir": "/v78/characters/haldir.webp",
  "glorfindel": "/v78/characters/glorfindel.webp",
  "cirdan": "/v78/characters/cirdan.webp",
  "sauron": "/v100/sauron-catalog-card.webp",
  "witch-king-of-angmar": "/v78/characters/witch-king-of-angmar.webp",
  "nazgul": "/v78/characters/nazgul.webp",
  "smeagol-gollum": "/v78/characters/smeagol-gollum.webp",
  "shelob": "/v78/characters/shelob.webp",
  "treebeard": "/v78/characters/treebeard.webp",
  "tom-bombadil": "/v78/characters/tom-bombadil.webp",
  "goldberry": "/v78/characters/goldberry.webp",
  "thorin-oakenshield": "/v78/characters/thorin-oakenshield.webp",
  "balin": "/v78/characters/balin.webp",
  "dain-ironfoot": "/v78/characters/dain-ironfoot.webp",
  "bard-the-bowman": "/v78/characters/bard-the-bowman.webp",
  "beorn": "/v78/characters/beorn.webp",
  "thranduil": "/v78/characters/thranduil.webp",
  "smaug": "/v78/characters/smaug.webp",
  "isildur": "/v78/characters/isildur.webp",
  "elendil": "/v78/characters/elendil.webp",
  "anarion": "/v78/characters/anarion.webp",
  "gil-galad": "/v78/characters/gil-galad.webp",
  "celebrimbor": "/v78/characters/celebrimbor.webp",
  "elros": "/v78/characters/elros.webp",
  "ar-pharazon": "/v78/characters/ar-pharazon.webp",
  "tar-miriel": "/v78/characters/tar-miriel.webp",
  "beren": "/v78/characters/beren.webp",
  "luthien": "/v78/characters/luthien.webp",
  "thingol": "/v78/characters/thingol.webp",
  "melian": "/v78/characters/melian.webp",
  "turin-turambar": "/v78/characters/turin-turambar.webp",
  "hurin": "/v78/characters/hurin.webp",
  "morwen": "/v78/characters/morwen.webp",
  "nienor": "/v78/characters/nienor.webp",
  "tuor": "/v78/characters/tuor.webp",
  "idril": "/v78/characters/idril.webp",
  "turgon": "/v78/characters/turgon.webp",
  "maeglin": "/v78/characters/maeglin.webp",
  "earendil": "/v78/characters/earendil.webp",
  "elwing": "/v78/characters/elwing.webp",
  "feanor": "/v78/characters/feanor.webp",
  "finrod-felagund": "/v78/characters/finrod-felagund.webp",
  "fingolfin": "/v78/characters/fingolfin.webp",
  "maedhros": "/v78/characters/maedhros.webp",
  "morgoth": "/v78/characters/morgoth.webp",
  "huan": "/v78/characters/huan.webp",
} as const;

export type V78CharacterPortraitSlug = keyof typeof v78CharacterPortraits;
export type V78PortraitVariant = "catalog" | "detail" | "search";

export function getV78CharacterPortrait(slug: string, _variant: V78PortraitVariant = "catalog") {
  return v78CharacterPortraits[slug as V78CharacterPortraitSlug] ?? "/v102/gandalf-catalog-card.webp";
}
